### ISSUE TITLE
어린용사

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#106]
![18_12](https://cloud.githubusercontent.com/assets/12267115/10013053/d7300512-6148-11e5-92bf-74005d770113.jpg)

스케치입니다

**Comment by horace-velmont** [comment]
좋다 굳 ~ㅋㅋ

**Comment by kangk64** [comment]
bust_이름_01  무표정
bust_이름_02  행복
bust_이름_03  웃음(씨익)
bust_이름_04  화남
bust_이름_05  짜증
bust_이름_06  아픈
bust_이름_07  슬픔
bust_이름_08  걱정
bust_이름_09  한숨
bust_이름_10  놀람
bust_이름_11  억지웃음(과장된)
bust_이름_12  침울
bust_이름_13  술취한

![bust_yongsa2_01](https://cloud.githubusercontent.com/assets/12267115/10027022/bf1bc1f8-619f-11e5-9b19-0a4d6d1a7c1a.png)
![bust_yongsa2_02](https://cloud.githubusercontent.com/assets/12267115/10027018/bf18960e-619f-11e5-94bc-4e336cc3a70c.png)
![bust_yongsa2_03](https://cloud.githubusercontent.com/assets/12267115/10027019/bf18ba6c-619f-11e5-8818-39046715e6b2.png)
![bust_yongsa2_04](https://cloud.githubusercontent.com/assets/12267115/10027020/bf1903c8-619f-11e5-8790-0bafd8d9859f.png)
![bust_yongsa2_05](https://cloud.githubusercontent.com/assets/12267115/10027025/bf3c531e-619f-11e5-9f0e-09722dd3e0b4.png)
![bust_yongsa2_06](https://cloud.githubusercontent.com/assets/12267115/10027028/bf4036d2-619f-11e5-8ec8-d508cc17350e.png)
![bust_yongsa2_07](https://cloud.githubusercontent.com/assets/12267115/10027024/bf3a308e-619f-11e5-9b27-ad9b429042e5.png)
![bust_yongsa2_08](https://cloud.githubusercontent.com/assets/12267115/10027026/bf3ddb6c-619f-11e5-937a-9717268d6e98.png)
![bust_yongsa2_09](https://cloud.githubusercontent.com/assets/12267115/10027027/bf4025f2-619f-11e5-8509-b3f0994ecebf.png)
![bust_yongsa2_10](https://cloud.githubusercontent.com/assets/12267115/10027029/bf44c166-619f-11e5-8886-fca3a81c97d6.png)
![bust_yongsa2_11](https://cloud.githubusercontent.com/assets/12267115/10027030/bf5b4f6c-619f-11e5-9e15-645f057310e3.png)
![bust_yongsa2_12](https://cloud.githubusercontent.com/assets/12267115/10027021/bf1a6ae2-619f-11e5-975d-0fe3c122b38a.png)
![bust_yongsa2_13](https://cloud.githubusercontent.com/assets/12267115/10027023/bf1fb632-619f-11e5-9791-a6f238596ea6.png)

**Comment by stemkill** [comment]
허헣 귀여억여엉ㄱ

**Comment by horace-velmont** [comment]
색감 좋음
