### ISSUE TITLE
버려진골렘

### ISSUE THREAD

**Issue by gyqls0309** [CienProject2014/OneLevelHero_GraphicTeam#11]
버려진골렘

**Comment by gyqls0309** [comment]
![default](https://cloud.githubusercontent.com/assets/9035096/5754037/3bc4ad62-9cd6-11e4-984b-3d59cd996a90.png)

**Comment by horace-velmont** [comment]
색감만 약간 수정해주면 좋을것같습니다.
입부분을 다른 색과 동일하게 가져가거나 좀더 무난한 색상이면 좋겠네요
