### ISSUE TITLE
보르티세

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#14]
상반신은 호리호리한 여성의 몸
하반신은 거대한 뱀의 형상
비닐은 푸른빛
머리카락은 짙은 묵색(혹은 갈색)
황금색 뱀의 눈을 가짐
거대한 삼지창과 판금 갑옷을 장비
성별 : 여
나이 : 25
키 : 172
몸무게 : 427
잔인 포악함

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/5898297/7cb51e74-a591-11e4-86e9-67d78b7fa312.png)
판금 갑옷이 뭔지.... 여러모로 신경쓰이지 못한 부분이 있습니다만은, 차차 수정해 나가겠습니다. 뱀꼬랑지를 생각해낸 분은 저에게 사과해주세요. 개어려움.

**Comment by horace-velmont** [comment]
하반신은 비늘로 처리할예정?

**Comment by stemkill** [comment]
그래야겟습니다만은, 제가 비늘같은걸 그려본적이 없어서 가능할 지 모르겠습니다. 여차하면 색을 덮은뒤에, 비늘이라는 느낌을 주는 표시를 해 줄 생각입니다. 물고기처럼요.

**Comment by zingzing2323** [comment]
우와....멋있어요 ! 굿굿

**Comment by soyagok11** [comment]
비늘 텍스쳐 따와서 입히시져

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/7937618/18715adc-097c-11e5-8a6c-7e4c336ec9bb.png)
![3](https://cloud.githubusercontent.com/assets/10277004/7937623/1e3ca480-097c-11e5-996f-57318edfbf3a.png)

크리핑을 시도하지 않은 무난한 버전과 크리핑을 시도한 대비가 강한버전이 있습니다. 둘중에 아무거나 골라서 사용해주시기 바랍니다. 다시는 이런 복잡한 그림 그리고싶지 않습니다.

**Comment by kangk64** [comment]
위에거 좋아보여요 ㅇㅅㅇ  채색법이 진화한다!?

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9171486/e4555ae4-3fa6-11e5-9709-8813232205e3.png)
클리어
