### ISSUE TITLE
메아

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#17]
갈색 롱헤어
허름한 면 옷(평민복) 
커다랗고 동그란 갈색 눈이 특징이다
항상 웃는 상이라 입은 보통 때도 살짝 미소 짓고 있음 
귀여운 외모와 어울리게 애교도 많다.

성별 : 여
키 : 166
몸무게 : 53
활기참
애교
긍정적
낯가림 없음

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/5920341/4f836804-a67f-11e4-889a-f4df5b36aaf7.png)

**Comment by stemkill** [comment]
평민복이라고 했지만 그리다보니 가죽자켓이 되어버렸습니다. 죄송합니다. 애교적인거야 뭐 원래 대사치는데서 해줄 수 있다고 생각합니다. 좀 사무적인 느낌이 되었습니다만은, 약간 배꼽이 드러난 주변으로 치마를 둘러그림으로서 어린느낌을 살리려고 했습니다.

**Comment by zingzing2323** [comment]
발이 좀 큰듯하지만 귀여운설정답게 귀엽귀엽하네요!

**Comment by horace-velmont** [comment]
몸무게가 53같진않군요..ㅋㅋ

**Comment by stemkill** [comment]
열아홉 청춘 생명력 넘치는 그런 분위기라고 생각햇는데 아닌가요

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/7897690/c962c9f2-071f-11e5-9e6b-55f44c285d9e.jpg)

**Comment by kangk64** [comment]
귀엽.ㅎㅎㅎ

**Comment by horace-velmont** [comment]
왕발녀ㅋㅋ

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/8647796/2bb517a2-2996-11e5-8833-1876bd5b827e.png)

**Comment by soyagok11** [comment]
![default](https://cloud.githubusercontent.com/assets/6358827/8760146/374b2fc0-2d47-11e5-937c-34d0ab9a85b4.png)

배경 투명한 메아 png 재업로드

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9171444/8a46a4c2-3fa6-11e5-914c-8202e1b4f981.png)
클리어
