### ISSUE TITLE
미우

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#18]
백옥 같은 피부 군데군데 검댕이가 묻어있음 
고양이 귀
푸른색 눈동자가 특징
표정 변화가 다양하며 동그란 눈
옷은 다 떨어진 넝마 같은 옷
금발 롱헤어
성별 : 여
나이 : 12
키 : 145
몸무게 : 30
순수
엉뚱함
귀여움
수인종(고양이)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/5935335/2f4cd37e-a71d-11e4-9cf0-e7d71fb93c85.png)

**Comment by Redrock912** [comment]
멋짐 설정이 몸무게 30이었다니 ;;

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/7984400/def3252c-0b03-11e5-891c-803603ffb451.png)

**Comment by kangk64** [comment]
뭔가 이름이랑 잘 어울려요 ㅎㅎ

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9171438/76ec3ffe-3fa6-11e5-86b6-f5bb00d92262.png)
클리어
