### ISSUE TITLE
플레챠

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#25]
어깨까지 내려오는 붉은 단발머리
다듬지 않아 삐쭉삐쭉 길이가 일정치 않음
자주빛 후드로 위에 고양이귀
꼬리가 길게 나 있으며 무늬는 얼룩덜룩함
눈매는 날카로운 고양이 눈이며 등에는 장궁과 화살
허리엔 단도가 장비돼 있다
활을 잡는 왼손은 가죽(or 건틀릿)으로 싸매져 있다

성별 : 여
나이 : 23
키 : 152
몸무게 : 42
과묵
냉철
수인종(고양이)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/6062203/350a104a-ad91-11e4-8ffe-88dd423e65fd.png)
대충한부분은 내일 하겠습니다.

**Comment by gimari** [comment]
![default](https://cloud.githubusercontent.com/assets/12236541/8793075/1a5c83ca-2fac-11e5-92a1-c7f8ab4c4140.png)

완성2
저번회의때 다시 그리셔야한다고 해서 그렸습니다
