### ISSUE TITLE
카디스 공작

### ISSUE THREAD

**Issue by Redrock912** [CienProject2014/OneLevelHero_GraphicTeam#27]
올백머리(잿빛)
황금색 실로 수놓아진 비단옷 
살짝 수척한 얼굴(아파보임)
왼쪽 가슴엔 가문을 상징하는 검과 방패가 교차된 문양이 달려 있음
처진 갈색눈.

![img_0085](https://cloud.githubusercontent.com/assets/10278051/6102187/673c7f90-b074-11e4-995c-f70ba792cdb0.JPG)

**Comment by Redrock912** [comment]
완성
![default](https://cloud.githubusercontent.com/assets/10278051/6394246/93aa049c-be13-11e4-88ba-35e088c85e54.png)

**Comment by xzvfinet** [comment]
오.. 형도 그림실력이 일취월장하시는거같아요
