### ISSUE TITLE
홀랜드

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#29]
넘긴 흰머리

흰눈썹으로 인해 눈이 보이지 않는다

흰 수염

복장은 모자를 제외한 대주교 복장(흰색 가운 등)

성별 : 남
나이 : 58
키 : 171
몸무게 : 68

인망이 넓은 교단의 장.

넓은 마음과 이해심.

신에 대한 절대적인 믿음을 가지고 충실하게 선을 베품.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/6143536/d7178bf8-b20d-11e4-8385-09408f349c98.png)

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/8328317/cb06d66a-1aaa-11e5-85c1-ebb90e84d5fc.png)

**Comment by soyagok11** [comment]
![Uploading 홀랜드.png…]()

배경 투명한 png 재업로드

**Comment by soyagok11** [comment]
![default](https://cloud.githubusercontent.com/assets/6358827/8760144/1da9dd50-2d47-11e5-8e8c-e7eee2b86889.png)

배경 투명한 홀랜드 png

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9171416/4a6b17e8-3fa6-11e5-97cf-3b166ca8db30.png)
클리어
