### ISSUE TITLE
주모

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero_GraphicTeam#3]
이름 : 주모(barmaid)
40대의 주점 주인인 뚱뚱한 아줌마. 키는 165 정도. 주황색 곱슬 머리를 머리 위에
서 묶음. 흰 피부. 검은 눈동자. 작업용 갈색 원피스에 흰색 앞치마.

**Comment by horace-velmont** [comment]
![jumo1](https://cloud.githubusercontent.com/assets/3744320/5625471/aab3ce3e-95be-11e4-9d95-462f77a5f959.jpg)
![jumo1-2](https://cloud.githubusercontent.com/assets/3744320/5625472/ac4e5750-95be-11e4-912b-c02b29cb6019.jpg)

**Comment by horace-velmont** [comment]
색감이 다른데 어느걸로 할지 고민중

**Comment by horace-velmont** [comment]
설정 정보좀 올려주시죠

**Comment by stemkill** [comment]
설정상 많은 부분의 배색이 바뀌었습니다. 40대 아줌마인점은 그대로입니다. 2개의 이미지 파일 중 위의 그림을 사용할 생각이며, 노을을 배경으로 아래 이미지를 사용할 수 있습니다.

**Comment by stemkill** [comment]
![3](https://cloud.githubusercontent.com/assets/10277004/8648078/90729442-2998-11e5-9d41-4659ab9cca7d.png)
