### ISSUE TITLE
리리스 (어린시절)

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#33]
푸른 눈동자와 노란 머리칼

평소 자신없는 표정

복장은 흰색 원피스에 맨발임

성별 : 여
나이 : 12
키 : 151
몸무게 : 46

겁많고 눈물이 많음.

외로움을 잘 타고 돌아가신 모친을 그리워함.

평소 소극적인 말투를 씀.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/6618439/4dffec88-c906-11e4-8244-c6bc0dc4f817.png)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8023815/10c27a80-0d57-11e5-89bf-756915c7f5d0.png)

**Comment by horace-velmont** [comment]
기획과 상관없이 귀여운거 더 그려주시죠

**Comment by kangk64** [comment]
우물쭈물 귀엽.ㅋㅋㅋㅋㅋ

**Comment by stemkill** [comment]
전 효율덕후라서...

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9171407/38d804c8-3fa6-11e5-9f25-111009b096e7.png)
클리어
