### ISSUE TITLE
네펠

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#35]
여 / 27세 / 168cm / 58kg / 윈터폴

//

차가운 눈빛과 비웃는 듯한 표정
노란 눈동자와 붉은 머리칼
양쪽에 굽은 뿔이 솟아나있음
허리춤에 검은 날개가 있다.
스페이드 모양의 꼬리가 있다.
무기는 거대한 낫
(스토리상 모든 리리스를 제외한 모든 서큐버스들은 
가슴이 작다. →B컵)

![01](https://cloud.githubusercontent.com/assets/12236541/8910178/46d6edc8-34c0-11e5-9091-678c63832efe.png)
![04](https://cloud.githubusercontent.com/assets/12236541/8910148/1f1a12ec-34c0-11e5-8499-a790b43fb0a6.png)
![05](https://cloud.githubusercontent.com/assets/12236541/8910149/1f84883e-34c0-11e5-82c3-b46c1e8aabc7.png)
![06](https://cloud.githubusercontent.com/assets/12236541/8910150/1fefcd7e-34c0-11e5-870a-8e14397afec9.png)

표정 위에서부터 차례대로 01(03), 04, 05, 06

**Comment by horace-velmont** [comment]
설정 및 각종정보도 같이 올려주셈 ㅋㅋㅋ closed된 채대언 작품들처럼

**Comment by horace-velmont** [comment]
구분하자면 NPC인건가요? 오른쪽 라벨에서 분류를 고를 수 있습니당

**Comment by gimari** [comment]
수정했습니다!

**Comment by horace-velmont** [comment]
와우 고퀄

**Comment by soyagok11** [comment]
위험한 표정이 있는데ㅋㅋㅋ

**Comment by soyagok11** [comment]
참고로 B컵이 밑가슴둘레+12.5센치이므로 저정도 크기라면 C컵을 약간 상회할지도 모름.
^오^

**Comment by gimari** [comment]
상체를 치켜올려서 커보이는것이라고 합시다

**Comment by gimari** [comment]
완전리워크됨
