### ISSUE TITLE
엘 이브 아오닌

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#37]
aonin
여
897(89)세
키 155
몸무게 44
소속 엘프의 숲

꼬부랑 할머니
은발
엘프귀
깊은 눈동자
잘 정돈된 머리
긴 소복같은 옷
초록색 옷
두 손을 소매에 넣고 있음

연륜
침착함
상황을 잘 정돈
온화한 미소
자연의 섭리 중시
해탈한 듯한 표정

**Comment by kangk64** [comment]
![18_1](https://cloud.githubusercontent.com/assets/12267115/7580413/dd8e32aa-f8af-11e4-8f19-deffa7398278.jpg)

**Comment by horace-velmont** [comment]
ㅋㅋㅋㅋ해탈한표정

**Comment by kangk64** [comment]
![Uploading 엘이브아오닌_01.png…]()

**Comment by kangk64** [comment]
![_01](https://cloud.githubusercontent.com/assets/12267115/7670845/fcd850d4-fcef-11e4-87a9-80f68e90f9fe.png)

**Comment by horace-velmont** [comment]
지적할거없이 잘그리셨네용.. 왠지 촌장님과 좋은 한쌍인 느낌..
