### ISSUE TITLE
오베른 경비병

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#4]
오베른 경비병
경비병(남)
남. 16세. 어린애처럼 생긴 경비병. 말투가 어른스러워 어울리지 않는다. 하지만 행
동은 어린애같다. 자신이 45살이라고 우기고 있지만 사실 경비병이 된 지 얼마 안 
된 꼬맹이다.

디자인 : 바랜 은색의 체인 메일을 입고 있다. 투구는 왼손에 들고 있다. 키는 135. 
머리 디자인과색깔은 마음대로.

**Comment by stemkill** [comment]
채색 전
![default](https://cloud.githubusercontent.com/assets/10277004/5626190/5b0fd2a8-95cb-11e4-83b1-a7288b426fcd.jpg)

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/5628992/9667ef36-95f1-11e4-9274-74ee8c8e5d3c.jpg)

**Comment by stemkill** [comment]
![3](https://cloud.githubusercontent.com/assets/10277004/5632710/288479f8-9614-11e4-80b8-aa6b4db01af5.jpg)
많은 부족한 부분이 있습니다만은... 특히 체인메일의 표현이라던가 하는것은 아직 수정의 여지가 남아있으므로, 다른부분을 지적해주시기 바랍니다. 표정이라던가, 그런부분은 언제든지 수정할 수 있습니다. 물론 이게 최종이긴 합니다만은, 업데이트가 가능하다는 표현이 맞겠습니다. 새로 시도해본 갑옷의 색칠은 아직 미숙하고, 시간상 비효율적이므로 다음부턴 최대한 간단한 채색으로 하는방향을 택하겠습니다. 채색 시부랄...

**Comment by horace-velmont** [comment]
머리삔은 동네 여자아이가 꼽아준건가요?

**Comment by stemkill** [comment]
![4](https://cloud.githubusercontent.com/assets/10277004/5641282/470a3e02-9679-11e4-94e4-3bda08145900.jpg)

잘 모르겠습니다. 누나가 꼽아줫거나, 동네 여자아이가 꼽아줫거나 둘중에 하나일것입니다.

**Comment by soyagok11** [comment]
얘도 좌우폭을 좀 줄이는 편이 낫지않으려나?

**Comment by stemkill** [comment]
일부러 갑옷의 무거운 느낌을 주기위해 좀 비대해보이게 그렸습니다

**Comment by horace-velmont** [comment]
영어 이름도 부탁드립니다

**Comment by stemkill** [comment]
오베른 guard

**Comment by horace-velmont** [comment]
oberon guard

**Comment by stemkill** [comment]
![4](https://cloud.githubusercontent.com/assets/10277004/8648041/492f6eb6-2998-11e5-8a8c-fa31d038e5ea.png)
