### ISSUE TITLE
켈렌

### ISSUE THREAD

**Issue by MakaJJang** [CienProject2014/OneLevelHero_GraphicTeam#40]
![default](https://cloud.githubusercontent.com/assets/12393498/7566410/916af634-f831-11e4-8f05-5f98f6b3d5fb.png)

**Comment by horace-velmont** [comment]
헉.. 이렇게빨리완성하신건가요?  퀄이랑 완성도가 장난아니네요 ㅎㄷㄷ;

**Comment by NakOh** [comment]
멋졍
