### ISSUE TITLE
네펠 (어린시절)

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#41]
14살/155cm/49kg

//

눈가 상처가 없음
차가운 눈빛과 비웃는 듯한 표정
표정에 잔인함과 포악함이 그대로 드러남.
항상 리리스를 멸시하고 무시함.
광기어린 표정을 자주 지으며 피를 핥는 습관이 있음.

![childnephell](https://cloud.githubusercontent.com/assets/12236541/8751212/b1508d30-2ce6-11e5-99dc-8b6e886d185b.png)
![childnephellangry](https://cloud.githubusercontent.com/assets/12236541/8751214/b219f8dc-2ce6-11e5-8913-712020178509.png)
![childnephellannoy](https://cloud.githubusercontent.com/assets/12236541/8751215/b2ffbb88-2ce6-11e5-98dd-ff8902dfcbb4.png)
![childnephelllaugh](https://cloud.githubusercontent.com/assets/12236541/8751216/b3dcce56-2ce6-11e5-8ee1-c5511cb1496e.png)
![childnephelllaugh1](https://cloud.githubusercontent.com/assets/12236541/8751276/0432eb38-2ce7-11e5-8627-cda75d48be64.png)
![childnephellpain](https://cloud.githubusercontent.com/assets/12236541/8751280/04c78040-2ce7-11e5-9bc5-4afebec5fe50.png)

표정 : 위에서부터 기본/화남/짜증/행복/웃음/아픔

**Comment by horace-velmont** [comment]
표정에 있어서 비열하고 잔혹한 느낌이 덜 드네요 오히려 착해보이는..? 좀더 눈가의 인상을 강하게 바꾸면 좋을 것 같습니다. 그리고 155치고는 롱다리네용 ㅋㅋㅋ
