### ISSUE TITLE
얄 루니스 로이

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#42]
성별 : 남
나이 : 297(29)
신장 : 195cm
몸무게 : 69kg
미라지 포트
은빛의 장발
긴 엘프귀
초록색의 얇은 옷
날카로운 눈매
표정 변화가 거의 없음
백옥같은 피부
푸른 빛의 눈동자
조용함
신의를 중시
날카로움
인간에 대한
깊은 불신

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/7705170/97dbf156-fe7d-11e4-9909-674e8dd915ce.jpg)

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/7860622/9773df9e-0585-11e5-8349-f8b813751e41.jpg)

**Comment by stemkill** [comment]
![3](https://cloud.githubusercontent.com/assets/10277004/7860700/4d595b0e-0586-11e5-9b3e-a1a25ecc9ca1.jpg)

**Comment by kangk64** [comment]
개인적으론 아래거 색감이 좋아요

**Comment by stemkill** [comment]
![4](https://cloud.githubusercontent.com/assets/10277004/7896202/38faf49e-06ec-11e5-90a2-e39df957f009.jpg)
![5](https://cloud.githubusercontent.com/assets/10277004/7896205/3f6f7e26-06ec-11e5-8b17-e9036faa64ea.jpg)
![6](https://cloud.githubusercontent.com/assets/10277004/7896206/45a1314a-06ec-11e5-864c-d14761d5eedd.jpg)

완성입니다.

첫번째는 원본. 두번째는 갈색 오버레이 적용. 세번째는 갈색 오버레이 적용 후 한번더 색을 죽인 버전입니다.
마음에 드시는걸로 써주시면 감사하겠습니다.

**Comment by horace-velmont** [comment]
힙합보이

**Comment by dbstn003** [comment]
2번째꺼가 좋은 듯

**Comment by stemkill** [comment]
![4](https://cloud.githubusercontent.com/assets/10277004/8647703/61971f56-2995-11e5-8855-fdf1f9bce0f9.png)
![5](https://cloud.githubusercontent.com/assets/10277004/8647707/67795d62-2995-11e5-99a0-2aef425a6cf8.png)
![6](https://cloud.githubusercontent.com/assets/10277004/8647711/6bdfa640-2995-11e5-9f1d-e8989ad5ed56.png)
픙픙

**Comment by soyagok11** [comment]
![default](https://cloud.githubusercontent.com/assets/6358827/8760136/d91b5e48-2d46-11e5-904b-e92cc71748cd.png)

배경 투명한 png 재업로드

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9171393/1981a0c0-3fa6-11e5-88f3-4cefdf0bd068.png)
클리어
