### ISSUE TITLE
예티

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#43]
![_](https://cloud.githubusercontent.com/assets/12267115/7752726/1bc10cfa-001c-11e5-9e71-47c53a23cea6.jpg)

**Comment by kangk64** [comment]
티베트나 히말라야에 산다고 전해지는 설남(雪男)의 일종. 키 1.5~2미터 정도로, 전신이 긴 털로 덮여 있고, 윗머리가 솟아 있다고 한다. 1951년에 한 등산가가 길이 30센티미터 정도의 발자국을 발견한 일로 일약 세계의 주목을 받아왔다. 이때의 발자국은 맨발이며 직립보행함을 알 수 있는 것이었다. 예티는 발자국 발견 이전부터 몇몇 목격자가 있었지만, 추한 거인이라는 점에서 인도 신화에 나오는 악마 락샤사라는 이름으로 불리는 경우도 있다.
[네이버 지식백과] 예티 [Yeti](환상동물사전, 2001.7.10, 도서출판 들녘)

**Comment by kangk64** [comment]
![default](https://cloud.githubusercontent.com/assets/12267115/7830559/7aa616c2-0489-11e5-92e8-5a4c84670fd1.png)

**Comment by horace-velmont** [comment]
귀여운 예티네요..ㅋㅋ

**Comment by dbstn003** [comment]
귀여워용
