### ISSUE TITLE
빙룡 안킬라스

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#44]
용, 몸길이 25m, 무게 32t

//

몸이 얼음으로 뒤덮임
거대한 날개
4개의 발
몸길이 25m, 몸 높이는 대략 7m
크아아 하고 울부짖는다
네펠에 의해 낮엔 깨어있고 밤엔 잠들음
윈터폴에 강한 추위를 몰고온 존재
브레스 공격, 앞발후려치기, 꼬리휘두르기 같은 넓은 공격을 사용하나 어쩐지 속도가 매우 느리다

![default](https://cloud.githubusercontent.com/assets/12236541/8654033/b127db6e-29c2-11e5-925b-58da7885c80d.png)

**Comment by dbstn003** [comment]
전투 이미지인거 같은데
플레이어를 바라보도록 얼굴이 정면인게 더 좋지않을까?

**Comment by gimari** [comment]
컨셉샷이라 전투이미지는 따로그려요

**Comment by stemkill** [comment]
오 최고로멋져요
