### ISSUE TITLE
서큐버스

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#45]
머리 양쪽의 뿔, 
허리춤 양쪽의 검은 날개, 
검은 스페이드모양의 꼬리,
가슴이 작다(B컵)
//

![1](https://cloud.githubusercontent.com/assets/12236541/9351296/1aae80d2-4693-11e5-8176-da34bc215777.png)

도중에 이상함을 느꼈는데 결국 끝까지와버림

**Comment by stemkill** [comment]
좀더 머리카락이 쭉쭉 길면 더 매력적일것같아요.
