### ISSUE TITLE
와이번

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#46]
작은 드래곤이라고 생각하면 되며, 몸집에 비해 날개가 크다.

//
참고이미지
:http://vignette2.wikia.nocookie.net/merlin1/images/0/06/Wyvern_from_the_myth.jpg/revision/latest?cb=20120227194838

반지의제왕 펠비스트의 이미지도 참고했습니다

![wyvern](https://cloud.githubusercontent.com/assets/12236541/8654008/7a4569ea-29c2-11e5-8a5e-d4f762bcdca5.png)

**Comment by stemkill** [comment]
뿔은 원래 없는건가요?

**Comment by gimari** [comment]
뱀 같다는 느낌을 주기 위해 뿔을 생략해봣습니다

**Comment by stemkill** [comment]
완전멋져
