### ISSUE TITLE
케인 휘스턴

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#47]
![20150530_200738](https://cloud.githubusercontent.com/assets/12267115/7897030/ef829616-0707-11e5-86de-34074747bead.jpg)

갑옷 어렵..=ㅅ=
왼다리 이상한거 수정할거에요

**Comment by kangk64** [comment]
20대후반
175cm
60kg

건장한체격. 피로. 신사적. 흑발. 촌장임과 동시에 폭동중이므로 투구없는 중갑. 가문의 상징. 의수.

아버지의 기대를 충족시켜주어야 한다는 중압감. 용사에 대한 열등감. 자신의 능력에 대해 과신하는 타입. 동료를 희생시키는데에 거리낌이없다 그리피스? 속내와 달리 표면적으로는 신사적. 친절해보인다.

제이크 질렌할
![fbe375ae1b9888b276fbab76d09b4dc5](https://cloud.githubusercontent.com/assets/12267115/7897048/83dc9ce4-0708-11e5-8ccf-4c2b0c6ed909.jpg)

**Comment by stemkill** [comment]
귀걸이나 머리띠나 그런것처럼 장신구가 있으면 더 과시적일거같아요.

**Comment by kangk64** [comment]
![_02](https://cloud.githubusercontent.com/assets/12267115/7897749/ec70d454-0722-11e5-8254-d10ee376769a.png)

**Comment by horace-velmont** [comment]
잘생겼다 존잘
