### ISSUE TITLE
젋은 케인

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#48]
-젊은케인
-남
-현재나이 - 10??
-키175cm??
-몸무게75kg??
-회상. 미들릿지
-현재보다 더욱 건장한 체격. 자신감. 경갑
-아직은 용사에 대한 열등감이 드러나지 않았다. 용사를 맡는것에 대한 부담과 거리낌, 동시에 용사를 아끼는 마음.
-좀더 벌크업

**Comment by kangk64** [comment]
![18_5](https://cloud.githubusercontent.com/assets/12267115/7902187/3d4fbfd4-07eb-11e5-9774-082c05060a27.jpg)

스트레스 받아서 그림이나 그렸습니다=ㅅ=ㅋㅋ
좀더 우락부락 ㄱㄱ???

*벌크업 : 흔히들 벌크 업은 근육의 크기를 키우는 것을 말합니다

**Comment by kangk64** [comment]
![18_6](https://cloud.githubusercontent.com/assets/12267115/7902220/cfbb43b0-07ec-11e5-9c63-7e6e126bb6c5.jpg)

![_02](https://cloud.githubusercontent.com/assets/12267115/7902234/4f592a24-07ed-11e5-98e9-d34806c676f5.png)

근육이 더 잘보여야하나... ~_~

아마 근육근육한데 20대후반 케인 젊을때라느거 보면 10대 후반?이나 중반일지 싶어서 저래 그렸습니다 일단

**Comment by nyamnym** [comment]
호우 듬직한 어깨

**Comment by HoraceVelmont** [comment]
그림이 잘못올라온것같아요

**Comment by HoraceVelmont** [comment]
케인이 휘스턴이군요 자살각...
늙은 케인 휘스턴사진이네용

**Comment by kangk64** [comment]
![_02](https://cloud.githubusercontent.com/assets/12267115/7983192/9522e424-0af8-11e5-8e92-cae7d1fa4f26.png)

**Comment by stemkill** [comment]
어맛 멋진남자!
