### ISSUE TITLE
단검을 든 소녀 암살자

### ISSUE THREAD

**Issue by soyagok11** [CienProject2014/OneLevelHero_GraphicTeam#5]
![kakaotalk_20150107_045841719](https://cloud.githubusercontent.com/assets/6358827/5640632/4d1474a6-966b-11e4-8c2c-e7e4c6c515b8.jpg)

이름 : 암살소녀(assassin girl)

**Comment by horace-velmont** [comment]
연보라색 부분 채색을 좀더 현실감 있게 바꾸었으면 좋겠습니다.

**Comment by stemkill** [comment]
기왕 몬스터고 암살잔데 도발적인 표정이 좋은것같습니다

**Comment by soyagok11** [comment]
표정을 바꾸는건 원작자에게 문의하시오(콩)

**Comment by soyagok11** [comment]
![20150107_2](https://cloud.githubusercontent.com/assets/6358827/5649699/4a0120aa-96db-11e4-8e42-015935871279.jpg)

보라게이

**Comment by horace-velmont** [comment]
서명을 지워주셔야 사용가능할 것같습니다 사용가능한 형태로 만들어주세요

**Comment by soyagok11** [comment]
쳇 들킴;

**Comment by soyagok11** [comment]
![20150107_done](https://cloud.githubusercontent.com/assets/6358827/5679925/7b16deb8-9849-11e4-870b-70308acedf29.jpg)

**Comment by horace-velmont** [comment]
used in OneLevelHero branch #106

**Comment by horace-velmont** [comment]
다음부터는 png파일로 저장 부탁드립니다
