### ISSUE TITLE
그리폰

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#50]
![18_7](https://cloud.githubusercontent.com/assets/12267115/7968032/15bbb8ee-0a69-11e5-9f96-f86c4937283b.jpg)

http://pds19.egloos.com/pds/201011/19/44/d0035544_4ce670423333e.jpg

20

griffon그리폰숲그리폰은 사자의 몸에 독수리의 머리와 날개가 달린 생명체로 알고 있음.

**Comment by nyamnym** [comment]
호우 멋잇네여

**Comment by horace-velmont** [comment]
리얼 개멋있네여..;;ㄷㄷ

**Comment by kangk64** [comment]
![_](https://cloud.githubusercontent.com/assets/12267115/9388214/0d4bdeaa-479f-11e5-9cbd-487b31ecfeef.png)
