### ISSUE TITLE
케인의 동료3ㅡ마른여자

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#51]
케인을 깊게 따른다. 스토리적으로 깊은 참여는 없지만, 현 미들릿지의 상황을 개선하려는 케인의 사상에 감복되어있다. 이후에 케인이 그들을 희생할때에 어쩔줄을 몰라한다
경갑ᆞ중갑
20대초중반
![18_8](https://cloud.githubusercontent.com/assets/12267115/8012939/192f5042-0c00-11e5-8c16-d6b31c537b0b.jpg)

**Comment by stemkill** [comment]
정말말랐네요!

**Comment by kangk64** [comment]
![default](https://cloud.githubusercontent.com/assets/12267115/8502217/1a69b918-21e8-11e5-91ee-061f2347498b.png)
