### ISSUE TITLE
프롤로그 4컷

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#52]
![1](https://cloud.githubusercontent.com/assets/12236541/8800867/4c015028-2ff1-11e5-82f1-bda29c53e68f.png)
![2](https://cloud.githubusercontent.com/assets/12236541/8805561/dc2670a0-300c-11e5-879f-a6852057e4a6.png)
![3](https://cloud.githubusercontent.com/assets/12236541/8805565/debbba64-300c-11e5-92ff-96baeef40cf1.png)
![4](https://cloud.githubusercontent.com/assets/12236541/8805566/e00346d0-300c-11e5-9e58-a7fadc389b75.png)

글:신벼리/그림:정종현

구도나 수정점 피드백부탁드립니다

**Comment by stemkill** [comment]
멋져용!

**Comment by dbstn003** [comment]
벼리형의 콘티때문에 원하던 것이 제대로 전달되지 않은 거같음

1컷 : 평화로운 마을(블랙우드 마을)이 있었다.
2컷 : 마왕이 나타났다. (기존의 1컷을 그대로)
3컷 : 평화로운 마을이 마왕성에 의해 위협받게 되었다. 그래서 용사일행이 찾아갔다.(기존의 2컷에서 나머지 일행 추가)
(용사일행 : 용사 + 파라스 + 리리스)
4컷 : 용사가 마왕에게 저주걸리고 용사일행이 마왕성 밖으로 튕겨져나갔다.(기존의 4컷에서 나머지 일행 추가)

**Comment by gimari** [comment]
![1](https://cloud.githubusercontent.com/assets/12236541/8381968/5605546a-1c6a-11e5-879c-c7681a4148e0.jpg)
![2](https://cloud.githubusercontent.com/assets/12236541/8381971/574828f2-1c6a-11e5-8bab-4bf145ad510d.jpg)
![3](https://cloud.githubusercontent.com/assets/12236541/8381972/58085424-1c6a-11e5-9c97-3e69b7e3fcfe.jpg)
![4](https://cloud.githubusercontent.com/assets/12236541/8381973/58c12e40-1c6a-11e5-9508-039be558cdc3.jpg)

1차컨셉수정

**Comment by horace-velmont** [comment]
요거 아직 진행중인 작업인가요?

**Comment by dbstn003** [comment]
채색 중임
