### ISSUE TITLE
마왕 - 전투모드

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#53]
마왕 전투모드 입니다.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8331690/98b18948-1ac4-11e5-80bc-6be8326d64a6.png)
언제 바뀔지 모릅니다

**Comment by stemkill** [comment]
![3](https://cloud.githubusercontent.com/assets/10277004/8396193/1a0a8eb2-1dd7-11e5-8116-b8c6152b5291.jpg)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8409504/46fa2702-1eb3-11e5-83e5-5ea8a9927172.jpg)

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/8433202/4abc3eda-1f7f-11e5-9a39-2aadeccd2e90.jpg)

**Comment by stemkill** [comment]
![4](https://cloud.githubusercontent.com/assets/10277004/8478350/ca1f3a1e-210b-11e5-9234-f2a0905977a8.png)

**Comment by dbstn003** [comment]
아.. 배꼽 보이는 줄 알고 좋았는데 ㅋㅋㅋ

**Comment by horace-velmont** [comment]
날개랑 신발 광택좀 넣어주세여

**Comment by stemkill** [comment]
![5](https://cloud.githubusercontent.com/assets/10277004/8510475/cbdbd156-2321-11e5-957f-512b4df17dd1.png)
![6](https://cloud.githubusercontent.com/assets/10277004/8510476/cfca3e9c-2321-11e5-8d32-f112301b6e36.png)

둘중에 암거나 쓰세영.

**Comment by stemkill** [comment]
![6](https://cloud.githubusercontent.com/assets/10277004/9171375/f63d4682-3fa5-11e5-9536-d97b65a7a50a.png)
![5](https://cloud.githubusercontent.com/assets/10277004/9171376/f711b872-3fa5-11e5-9c3e-25cb8409d015.png)
클리어어
