### ISSUE TITLE
몬스터-케르베로스

### ISSUE THREAD

**Issue by hwagom** [CienProject2014/OneLevelHero_GraphicTeam#54]
테스트 겸 올려봅니다!
![150626-2](https://cloud.githubusercontent.com/assets/13031302/8381530/4cc1f71c-1c67-11e5-8fb6-8458d8c86344.png)

**Comment by horace-velmont** [comment]
우왕 굿굿ㅋㅋㅋ
선이 약간 두꺼워서 조금 얇게 하면 좋을듯?

**Comment by hwagom** [comment]
![150626-3](https://cloud.githubusercontent.com/assets/13031302/8391272/5691f6de-1cf8-11e5-93b2-5aa6c58aebc9.png)
스트로크 없애봤습니다

**Comment by stemkill** [comment]
난 두꺼운게 좋읗덧,

**Comment by dbstn003** [comment]
선 얇은게 좋은 듯 깔끔해
