### ISSUE TITLE
리리스

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#55]
![01](https://cloud.githubusercontent.com/assets/12236541/8576158/2a72047c-25db-11e5-9329-640c78e0cc73.png)
![02](https://cloud.githubusercontent.com/assets/12236541/8576159/2baaec00-25db-11e5-9a72-a61ad517b1bd.png)
![03](https://cloud.githubusercontent.com/assets/12236541/8576162/2c81871a-25db-11e5-983a-a085f7de4b02.png)
![04](https://cloud.githubusercontent.com/assets/12236541/8576163/2d80132a-25db-11e5-853b-66bb2295fe63.png)
![05](https://cloud.githubusercontent.com/assets/12236541/8576164/2e12d78c-25db-11e5-8338-7c0f75e95e35.png)
![06](https://cloud.githubusercontent.com/assets/12236541/8576165/2ea9bd28-25db-11e5-8022-dec7ee191b39.png)
![07](https://cloud.githubusercontent.com/assets/12236541/8576166/2f3ce3e6-25db-11e5-9689-321b3ca82bb0.png)
![08](https://cloud.githubusercontent.com/assets/12236541/8576167/2fc11ad0-25db-11e5-896c-d25f8c014d11.png)
![09](https://cloud.githubusercontent.com/assets/12236541/8634560/6da09c40-2838-11e5-8eac-7d2bd27d3f9a.png)
![10](https://cloud.githubusercontent.com/assets/12236541/8634557/6497fbd4-2838-11e5-9036-baa12cc915f1.png)
![11](https://cloud.githubusercontent.com/assets/12236541/8634558/650f173c-2838-11e5-9823-5cbd537ccb07.png)
![12](https://cloud.githubusercontent.com/assets/12236541/8634559/659dfe34-2838-11e5-9192-ebcada801e5e.png)

위에서부터 차례대로 표정번호 01~12
어색한표정은 피드백바랍니다

**Comment by kangk64** [comment]
우옹 이뻥.ㅎㅎㅎㅎ +ㅅ+ㅎㅎ 다만 머...머리만 좀 컸으면..ㅠㅠ;;;넘 작아서 무섭.;

**Comment by gimari** [comment]
![default](https://cloud.githubusercontent.com/assets/12236541/8436268/e864e116-1f91-11e5-99a0-7ac81b34cf30.jpg)
비율수정!

**Comment by horace-velmont** [comment]
가슴부분이 살짝 어색한데 조금 아래있는느낌..?ㅋㅋㅋ

**Comment by gimari** [comment]
![default](https://cloud.githubusercontent.com/assets/12236541/8460656/666ece58-2061-11e5-898e-d916e8550513.jpg)

스케치완성-1차
