### ISSUE TITLE
파라스

### ISSUE THREAD

**Issue by milky1022** [CienProject2014/OneLevelHero_GraphicTeam#56]
파라스임당 퓨_퓨

![b21744b8-2055-11e5-8292-1716bde097e7](https://cloud.githubusercontent.com/assets/12381576/8461059/a1da3056-2064-11e5-887b-1db03eb8b01f.png)
![cf2211f4-2056-11e5-91df-f45615bac38f](https://cloud.githubusercontent.com/assets/12381576/8461058/a1d615ac-2064-11e5-8e70-7aaa9559ac47.png)

**Comment by stemkill** [comment]
KA - WAI!

**Comment by kangk64** [comment]
귀여워!!!!(근데 대검드는 무서운놈.ㅋㅋㅋ)
