### ISSUE TITLE
마왕 - 전투모드 2

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#58]

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8544845/bad7dbac-24e3-11e5-9549-45c74969ff60.png)
컨셉입니다.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8595678/199337e8-2685-11e5-91f0-1d79411b129f.png)

**Comment by dbstn003** [comment]
눈매 맘에 든다

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8631981/fb29196a-27c1-11e5-817c-c0958071b20b.png)
![default](https://cloud.githubusercontent.com/assets/10277004/8631983/0291d8d6-27c2-11e5-9ad9-efdda21fe577.jpg)
배경에 흰색을 깔았더니 이런일이. 맘에드는걸 쓰세용.

**Comment by horace-velmont** [comment]
날개의 양감이 부족합니다 3D 입체감을 부여해주세요

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8647683/20455158-2995-11e5-939a-c3de0614c5a8.png)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9171353/c2684424-3fa5-11e5-9421-c56e158cac6d.png)
클리어어
