### ISSUE TITLE
사서 에이미

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#59]
![default](https://cloud.githubusercontent.com/assets/12236541/8739810/abe3ca1c-2c7b-11e5-886e-ea3384fe65d9.png)

비율을좀 수정햇습니다

**Comment by horace-velmont** [comment]
귀엽네요.,ㅋㅋ 근데 이번에도 얼굴이 너무 작은듯..! 
다리랑 목굵기의 차이가 너무 심해요..ㅋㅋㅋㅋㅋㅋㅋ
