### ISSUE TITLE
와이지 촌장

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#6]
이름 : 와이지 촌장(waiji)
남. 나이 65세 즈음. 선탠한 듯 갈색이 감도는 피부와 검붉은 눈을 지녔다. 원형탈
모로 머리가 다 벗겨져 귀 근처에나 회색의 머리숱이 약간 남아있다. 하얀 콧수염
도 지니고 있으며 연갈색 지팡이를 짚고 다닌다. 키는 165정도로 인자하게 생겼으
며 외형만큼 인망이 높아 마을 사람들의 신뢰를 받고 있다.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/5643505/89877272-969c-11e4-8dd2-e25a6b1ecd09.jpg)

**Comment by stemkill** [comment]
![3](https://cloud.githubusercontent.com/assets/10277004/5649779/05bfca80-96dc-11e4-9c0d-2fb5ad3bb386.jpg)

옆으로 퍼졌다는 의견을 반영해 축소를 통한 성형을 하였습니다. 꽤나 성공적이었으며 좀더 어께가 굽어야한단 의견을 반영해 어께부분을 수정하였습니다. 전체적으로 어두침침하고 음험한 색깔로 작업되었으며, 피부톤 또한 나이를 반영해 칙칙한 색을 사용했습니다. 표정이 무섭긴 하지만 주어진 조건 내에서 최대한 인자하게 생기길 바라고 시도한 작품이니 이해해 주시기 바랍니다.

**Comment by soyagok11** [comment]
용사가 좀 쫄아있으려면 무서운것도 괜차는듯

**Comment by stemkill** [comment]
![3](https://cloud.githubusercontent.com/assets/10277004/8648025/194f630e-2998-11e5-9dc7-23fb96319261.png)
