### ISSUE TITLE
데임이스트

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#62]
![bust_deimeast_05](https://cloud.githubusercontent.com/assets/12267115/8651107/f51dcbf0-29b1-11e5-9e62-665255e78c7b.png)
![bust_deimeast_06](https://cloud.githubusercontent.com/assets/12267115/8651106/f51ca220-29b1-11e5-81c1-e3ee93ae91b8.png)
![bust_deimeast_01](https://cloud.githubusercontent.com/assets/12267115/8651105/f5195ffc-29b1-11e5-8193-f51a1733c34e.png)
![bust_deimeast_02](https://cloud.githubusercontent.com/assets/12267115/8651108/f53e6efa-29b1-11e5-97b0-be1fef10efc3.png)
![bust_deimeast_03](https://cloud.githubusercontent.com/assets/12267115/8651109/f53fffa4-29b1-11e5-8e51-b41aaadbd54c.png)
![bust_deimeast_04](https://cloud.githubusercontent.com/assets/12267115/8651110/f5436dce-29b1-11e5-8eb1-d91029ef6081.png)

**Comment by gimari** [comment]
첨에 얘가 파라스인줄알앗음
