### ISSUE TITLE
이름까먹음

### ISSUE THREAD

**Issue by kangk64** [CienProject2014/OneLevelHero_GraphicTeam#64]
![bust_the_04](https://cloud.githubusercontent.com/assets/12267115/8651164/371988a0-29b2-11e5-8a85-ab15f07636bf.png)
![bust_the_05](https://cloud.githubusercontent.com/assets/12267115/8651161/3714f628-29b2-11e5-97b1-1942cd6ca52b.png)
![bust_the_01](https://cloud.githubusercontent.com/assets/12267115/8651162/371849a4-29b2-11e5-8241-fbdfdaa20772.png)
![bust_the_02](https://cloud.githubusercontent.com/assets/12267115/8651165/3719ef66-29b2-11e5-83c1-925617782cf9.png)
![bust_the_03](https://cloud.githubusercontent.com/assets/12267115/8651163/37190de4-29b2-11e5-9498-632671e9fdb2.png)

**Comment by kangk64** [comment]
원본이 외장하드 고장나면서 사라진듯함..=ㅅ=;;.... 그래서 이름이 기억안남.ㅠㅠ;;; 누구더라~ㅅ~

**Comment by stemkill** [comment]
파라스 엄마잖아여

**Comment by kangk64** [comment]
파라스 엄마 맞나 긴가민가하긴 했는뎈ㅋㅋㅋ 이름이 있었는데 뭐였지.ㅠㅠㅠㅠ THE라고 저장은 되어있는데.=ㅅ=허허
