### ISSUE TITLE
레드로즈 백작

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#70]
레드로즈 백작
남
 키 182
몸무게 73
나이 62
하얗게 센 머리카락을 짧게 잘라 뒤로 넘기고 있다. 
콧수염이 있으며, 깔끔한 귀족풍 정장을 입고 있다. 인자한 듯 보이지만 
날카로움이 있는 갈색빛 눈. 날카로운 인상
겉보기엔 어질고 자애로워 보이지만 속내는 실리를 철저히 추구하는 인물.
 공과 사에 뚜렷하며 레드로즈 지역의 발전을 위해서는 어떤 희생도 마다않을 정도이다.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8718673/315eb512-2be1-11e5-8579-f1650681657a.png)
할아버지 몸관리 잘했어여.

**Comment by horace-velmont** [comment]
농부랑 너무 비슷하게 생겼는데 ㅋㅋㅋㅋㅋㅋ 귀족느낌을 더해주세요!

**Comment by stemkill** [comment]
귀족스런 채색으로 찾아뵙겠습니다

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8743232/ed719cc6-2ca7-11e5-864a-64f577ec7709.png)
![2](https://cloud.githubusercontent.com/assets/10277004/8743233/f0c1b0c8-2ca7-11e5-91a7-82251be6c16e.png)
![3](https://cloud.githubusercontent.com/assets/10277004/8743237/f4c37530-2ca7-11e5-8ebe-5fe6f196d6e9.png)
가장 알맞다고 생각되는 색을 골라서 써주시기 바랍니다.

**Comment by kangk64** [comment]
3번째!!(취향이 너무 칙칙한가..-ㅅ-)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9171124/09a408c0-3fa4-11e5-8191-89440316697b.png)
![3](https://cloud.githubusercontent.com/assets/10277004/9171125/09a6c9d4-3fa4-11e5-9373-b66ee9a699c4.png)
![2](https://cloud.githubusercontent.com/assets/10277004/9171126/09a89804-3fa4-11e5-9d54-cc38718e7bf7.png)
클리어
