### ISSUE TITLE
마을소년

### ISSUE THREAD

**Issue by yulim0** [CienProject2014/OneLevelHero_GraphicTeam#73]
![1 _](https://cloud.githubusercontent.com/assets/13298839/8760660/c6ddf718-2d64-11e5-903a-c68b72b763b7.png)

시트에 있는 설정 참고.

-갈색 머리카락을 동글동글하게 잘라 놨다. 푸른색 눈동자. 짧은 반팔 티셔츠에 발목까지 오는 바지를 입고 있다. 동글동글한 인상

-골목대장

**Comment by horace-velmont** [comment]
어..음.. 의상이랑 소품 컨셉이 중세판타지랑 좀 안맞지 않나싶네요...
근데 그래픽팀 다른 그림보니 다른그림도 뭐 조금씩 현대적 느낌이 있긴하네요 ㅋㅋㅋ

**Comment by gimari** [comment]
이쁜듯!

**Comment by stemkill** [comment]
으어억 엄청귀여워억!
