### ISSUE TITLE
몬스터 - 앤트

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#75]
저주받은 - 나무 요괴!

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8821398/482575ea-3098-11e5-9db6-4ff310494c24.png)
![2](https://cloud.githubusercontent.com/assets/10277004/8821401/4b6bf22e-3098-11e5-8ceb-63c0f9a7ca66.png)
저주받은 몬스터라면 이정도 포스는 되어야한다고 생각합니다.

**Comment by gimari** [comment]
윙크하고있는것같음

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9170361/0e64095c-3f9d-11e5-9f99-1bb18a45a5a9.png)
![2](https://cloud.githubusercontent.com/assets/10277004/9170360/0e621aa2-3f9d-11e5-9590-4288251bc36d.png)
32비트입니다.

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9171113/f1cb8eb2-3fa3-11e5-95bf-4bfec70d2925.png)
클리어어
