### ISSUE TITLE
멍청한 트윈헤드

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#77]
멍청하다는 설명이 붙었지만 뇌가 일반인의 두배이므로 위대한 게임 제작진과 신에비해 멍청하지만 우매한 인간보다 두배 똑똑한 트윈헤드입니다.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8870627/5a9933e0-322a-11e5-96f5-22312157cf15.png)
![2](https://cloud.githubusercontent.com/assets/10277004/8870632/601e7212-322a-11e5-9e0e-a000ed42cea7.png)

**Comment by gimari** [comment]
뇌가 2개라서 지능도 듀얼코어

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9170332/cea6dbaa-3f9c-11e5-83e6-46311fd71d78.png)
32비트입니다
