### ISSUE TITLE
카르네 바르워스

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero_GraphicTeam#8]
39세. 부인인 루미리아 못지 않게 수수한 옷차림이지만, 모자는 한껏 멋을 부려놓
았다. 붉은 깃털과 자수정으로 장식해 두었다. 파란 빛이 감도는 비로드를 걸치고 
있다. 수염은 콧수염과 턱수염을 길렀으며, 체구가 작은 편. 주황색을 띄는 눈빛이 
예사롭지 않다. (왕좌의 게임의 리틀 핑거랑 비스무리하게 생김)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/5857496/b02370da-a28f-11e4-8883-10b60d499ad0.jpg)

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/8063202/6945fb74-0f0e-11e5-8f2a-c2300f3da433.png)

**Comment by kangk64** [comment]
옷에도 약간 장식있으면 모자랑 갭이 덜할듯 싶습니다ㅇㅅㅇ

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/8129067/3bcc4b6a-1140-11e5-9d28-05661a7d6309.png)
잘 모르겠습니다.

**Comment by horace-velmont** [comment]
핑키핑키 하구먼 ㅋㅋ
