### ISSUE TITLE
네펠 2차변신

### ISSUE THREAD

**Issue by gimari** [CienProject2014/OneLevelHero_GraphicTeam#80]
![2](https://cloud.githubusercontent.com/assets/12236541/9081463/69fd250a-3b97-11e5-8770-0e4c59c9744e.png)

약점 : 스파크가 튀는 왼쪽 뿔

**Comment by soyagok11** [comment]
뿔이 너무 커서 미묘한듯ㅋㅋ

**Comment by gimari** [comment]
불멸의 수정이랑 합체한뒤라 일부러 뿔을 좀 기괴하게 크게 만들엇어여
