### ISSUE TITLE
식료품점 주인

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#82]
식료품점 주인입니다. 타블렛을 사용해봤어요. 존나빨리그렸네 생각해보니까.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9086691/ddd18cea-3bc0-11e5-9ee1-ea07e06ff369.png)
![2](https://cloud.githubusercontent.com/assets/10277004/9086694/e358737c-3bc0-11e5-9aa6-d9a53e46cbe7.png)

**Comment by gimari** [comment]
흠.. 대머리로 하니깐 뭔가 몬스터 같아요 머리숱을 탈모온것처럼 그려보는것은 어떤지?

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9148596/967503a6-3dbc-11e5-8f9e-27d2672b7061.png)

**Comment by horace-velmont** [comment]
zzzzzz 너무 어색해 발모제 바른거같음

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9170308/aaa9ab38-3f9c-11e5-8ea2-485a18968452.png)
32비트입니다.

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9171462/ab70b4da-3fa6-11e5-9184-4dfbdcb9f4aa.png)
클리어어
