### ISSUE TITLE
질나쁜 용병

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#83]
용병 아저씨입니다. 착한 아저씨라고 믿습니다.

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/9107347/891ba252-3c61-11e5-99c6-96061b60ecef.png)
![2](https://cloud.githubusercontent.com/assets/10277004/9107352/8eca3c90-3c61-11e5-9155-49a07c1fcfd3.png)

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9112937/e8ff7f74-3c8c-11e5-8bbe-624eb144854e.png)

**Comment by horace-velmont** [comment]
ㅋㅋㅋ 겁나 귀엽게생김

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9170510/8a299894-3f9e-11e5-8b25-0a9b659e4da0.png)

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/9171451/99186d64-3fa6-11e5-96dc-ece37707c42f.png)
클리어
