### ISSUE TITLE
바다의 마녀(미정)

### ISSUE THREAD

**Issue by stemkill** [CienProject2014/OneLevelHero_GraphicTeam#9]
누군가의 설정에 등장했던 바다의 마녀. 일러스트의 성격이 그와 상관없이 전개되어 전혀 다른 캐릭터가 되어 버렸다. 누군가 제발 주워가서 써주시길. 
방구석에 틀어박혀 이상한 만화에 빠져 산다. 직업은 못된 사람들의 못된 소원을 들어주며 인류를 괴롭히는(잘해봐야 동네사람들이지만) 마법을 부려주는 마법사. 최근에 마을 사람들을 괴롭힐 목적으로 인접한 바다에 폭풍을 일으켰으나 일이 커져 폭풍이 가라앉지 않게되어 골치다. 자기를 무찌르겠다고 나서는 녀석들도 문제지만, 동네 말썽꾸러기에 불과했던 자신을 무턱대고 숭배하는 무리가 생긴것. 그때문에 원래 방구석 폐인이던 성격은 더욱 심각해졌고, 일주일에 한번만 밖으로 나오는 등 행동하게 되었지만, 오히려 신비주의 성격을 더하게 되어 악당들로부터 인기만점.
용사일행이 방에 들이닥쳤을때 분명 침대에서 자빠지는 것을 보았지만, 바닥에 얼굴을 박은 자기 자신은 이것이 바다의 신에게 제사지내는 올바른 방식이고, 너희들은 그걸 방해하러 온 녀석들이라며 우긴다. 
나이 미정/키 166/성별 여/ 위치 미정

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/5703559/9a7afa82-9aab-11e4-8a5a-e8936b359a5a.jpg)

**Comment by stemkill** [comment]
![2](https://cloud.githubusercontent.com/assets/10277004/5703578/c386ad04-9aab-11e4-8583-0b5c8eac83bb.jpg)

**Comment by horace-velmont** [comment]
몬스터로 쓰고싶습니다

**Comment by stemkill** [comment]
![default](https://cloud.githubusercontent.com/assets/10277004/5721552/65db0e86-9b76-11e4-88e1-fc82b22f94af.png)
